# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy on Railway (Dev)

on:
  push:
    branches: ['dev']

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, typescript]

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Install Railway
        run: pnpm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
